#!/usr/bin/env python3
"""Build VN SRT from translations list. Each entry maps a chunk of EN blocks to one VN block."""
import re
import os

EN = os.path.expanduser("~/projects/Khiemdt/video-srt-promt/srt/game-theory/[English] Game Theory #26  The Holy Empire of AI.srt")
OUT = os.path.expanduser("~/projects/Khiemdt/video-srt-promt/srt-output/game-theory/[Vietnamese] Game Theory #26  The Holy Empire of AI.srt")

def ts_to_sec(ts):
    m = re.match(r"(\d{2}):(\d{2}):(\d{2})[,.](\d{3})", ts.strip())
    if not m: return None
    h, mn, s, ms = map(int, m.groups())
    return h*3600 + mn*60 + s + ms/1000

def sec_to_ts(sec):
    if sec < 0: sec = 0
    h = int(sec // 3600); sec -= h*3600
    m = int(sec // 60);   sec -= m*60
    s = int(sec)
    ms = int(round((sec - s) * 1000))
    if ms == 1000: s += 1; ms = 0
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"

def parse_en(path):
    with open(path, "r", encoding="utf-8-sig") as f:
        content = f.read()
    blocks = []
    for raw in re.split(r"\n\s*\n", content.strip()):
        lines = [l for l in raw.strip().split("\n") if l.strip()]
        if len(lines) < 3:
            continue
        try:
            idx = int(lines[0].strip())
        except ValueError:
            continue
        ts = lines[1].strip()
        text = " ".join(lines[2:]).strip()
        try:
            start_sec = ts_to_sec(ts.split("-->")[0])
            end_sec = ts_to_sec(ts.split("-->")[1])
        except Exception:
            continue
        blocks.append((idx, ts, text, start_sec, end_sec))
    blocks.sort(key=lambda b: b[0])
    return blocks

# (last_en_idx, vn_text) — VN block spans from previous block's end+1 to last_en_idx
# If last_en_idx == previous (None move), append-text not supported here
# Use sentinel last_en_idx negative to skip / cut earlier
TRANSLATIONS = [
    # Batch 1 — 0:00 to ~5:00 (EN blocks 1-110)
    (3,   "Học kỳ trước chúng ta đã tìm hiểu về các hội kín và mạt thế học, tức lịch sử bí mật."),
    (5,   "Học kỳ này chúng ta sẽ học về lý thuyết trò chơi."),
    (6,   "Trong tiết này tôi muốn nối hai chủ đề lại và chỉ cho các bạn thấy cách thế giới vận hành."),
    (8,   "Việc đầu tiên là điểm qua vài thuyết âm mưu phổ biến về cách thế giới vận hành."),
    (9,   "Và có nhiều biến thể khác nhau."),
    (11,  "Tôi sẽ trình bày một phiên bản rất đơn giản, rõ ràng nhất."),
    (14,  "Nhớ rằng nếu có gì các bạn không hiểu thì cứ đặt câu hỏi để nắm cho rõ."),
    (15,  "Vậy thì ta bắt đầu với Hiệp sĩ Dòng Đền."),
    (19,  "Hiệp sĩ Dòng Đền có lẽ là hội kín thành công nhất trên thế giới, được thành lập năm 1118."),
    (20,  "Tổ chức này ra đời như một phần của các cuộc Thập tự chinh."),
    (22,  "Khi đó những người Cơ Đốc hành hương đi đến Jerusalem thường bị cướp dọc đường."),
    (26,  "Hiệp sĩ Dòng Đền là một tổ chức tình nguyện được Vatican chỉ định để bảo vệ những người hành hương này."),
    (29,  "Theo thời gian, Hiệp sĩ Dòng Đền cũng trở thành một ngân hàng, nơi bạn có thể gửi vàng vào."),
    (33,  "Họ cấp cho bạn biên nhận, và khi bạn đến Jerusalem thì trả lại vàng cho bạn."),
    (37,  "Họ trở thành ngân hàng, và dần dần thành một tổ chức cực kỳ hùng mạnh, hội tụ chính trị, quân sự, tôn giáo và tài chính."),
    (41,  "Chính vì vậy mà năm 1314, Giáo hội Công giáo và vua nước Pháp đã đặt họ ngoài vòng pháp luật."),
    (44,  "Họ thiêu sống thủ lĩnh Jacques de Molay trên giàn hỏa, kết tội báng bổ vì thờ một thần giả tên là Baphomet."),
    (47,  "Các Hiệp sĩ Dòng Đền có mặt ở Jerusalem, nơi hội tụ mọi tôn giáo."),
    (52,  "Họ bắt đầu tò mò về các tôn giáo khác và dấn vào triết học Hermetic, tân Plato luận, triết học Ngộ đạo, tất cả bị Giáo hội Công giáo coi là dị giáo."),
    (53,  "Vậy nên đây là một tổ chức bị cấm."),
    (57,  "Người ta đồn rằng thay vì biến mất, Hiệp sĩ Dòng Đền đã tái xuất dưới hình thức Hội Tam Điểm Scotland."),
    (62,  "Tầm quan trọng của họ là về sau, họ đã tạo ra phong trào Cải cách, cùng với cuộc cách mạng."),
    (65,  "Họ âm mưu tạo ra Cách mạng Mỹ cũng như Cách mạng Pháp."),
    (66,  "Về cơ bản, họ tạo ra chính bản thân thời hiện đại."),
    (70,  "Họ đến kiểm soát nước Anh và lập ra Ngân hàng Anh, thứ đã tạo nên hệ thống tài chính hiện đại ngày nay."),
    (71,  "Sau đó họ tạo ra Thế chiến I."),
    (73,  "Thế chiến I dẫn đến Thế chiến II, và bây giờ họ đang âm mưu tạo ra Thế chiến III."),
    (76,  "Thế chiến III sẽ mở đường cho một chính phủ một thế giới đặt tại Jerusalem."),
    (78,  "Và nó sẽ được kiểm soát bởi một nhà nước A I giám sát dân thường."),
    (81,  "Đó là lý do chúng ta đang thấy các trung tâm dữ liệu được xây dựng khắp thế giới."),
    (85,  "Người ta cũng đồn rằng các Hiệp sĩ Dòng Đền đã biết cách giao tiếp với quỷ liên chiều không gian."),
    (86,  "Hay với Lucifer."),
    (89,  "Và muốn giao tiếp với quỷ thì bạn phải ký giao kèo với chúng qua hiến tế nghi lễ."),
    (91,  "Sau đó chúng có thể nhập vào bạn."),
    (95,  "Và đề nghị các bí mật, ví dụ cách sống mãi, cách trẻ mãi, hay cách xây dựng công nghệ vĩ đại."),
    (96,  "Chúng cũng có thể chỉ cho bạn cách chế tạo vũ khí hạt nhân."),
    (102, "Người ta đồn rằng toàn bộ mục đích của chính phủ một thế giới và nhà nước A I giám sát là để đưa những sinh thể liên chiều này vào thế giới của chúng ta, để giới tinh hoa có thể sống mãi và hợp nhất với chúng."),
    (106, "Cũng có người đồn rằng các Hiệp sĩ Dòng Đền có gốc gác xa tận La Mã và 13 gia tộc, về sau trở thành một phần của Venice."),
    (110, "Vậy là có rất nhiều biến thể của thuyết âm mưu này về cách thế giới vận hành."),

    # Batch 2 — ~5:00 to ~10:00 (EN blocks 111-220)
    (112, "Bây giờ, thuyết âm mưu này có rất nhiều vấn đề."),
    (115, "Thứ nhất, thực ra không có bằng chứng nào cho thấy điều này là đúng."),
    (116, "Chúng ta không biết liệu quỷ có thực sự tồn tại hay không."),
    (118, "Thực ra không có bằng chứng nào cho thấy quỷ tồn tại."),
    (120, "Không có bằng chứng cho thấy đây là một âm mưu khổng lồ kéo dài cả nghìn năm."),
    (123, "Thứ hai, bản thân giới tinh hoa không biết điều này là thật."),
    (127, "Người ta tin chuyện này là thật, nhưng nếu bạn đến nói chuyện với những người có quyền lực thực, họ sẽ thấy đây là chuyện hoàn toàn nhảm nhí."),
    (129, "Thứ ba, thuyết này phản lịch sử."),
    (133, "Nghĩa là nó là một phiên bản quá đơn giản về cách mọi thứ vận hành, không tính đến nhiều yếu tố khác."),
    (135, "Hơn nữa, điều ta học trong lớp này là lý thuyết trò chơi, và thuyết âm mưu này cũng phản lý thuyết trò chơi."),
    (141, "Bởi vì điều bạn học được là khi con người có quyền lực, họ trở nên kiêu ngạo, ngông cuồng, ngu xuẩn, nên rất phổ biến chuyện người quyền lực trỗi dậy rồi sa ngã."),
    (142, "Đó đơn giản là quy luật sắt của lịch sử."),
    (144, "Vì những lý do đó, chúng ta biết thuyết này không đúng sự thật."),
    (147, "Đồng thời, có những điểm trong thuyết này rất thuyết phục."),
    (148, "Vậy hãy điểm qua vài điểm trong số đó."),
    (151, "Điều đầu tiên khiến thuyết này thuyết phục là nó rất trực quan."),
    (153, "Trực quan nghĩa là khi tôi kể cho ai đó, họ thấy nó hợp lý."),
    (156, "Nó hợp lý hơn nhiều so với lịch sử mà ta được dạy trong trường, hơi kỳ phải không?"),
    (157, "Không có gì trong đó đúng cả, nhưng nó trực quan."),
    (162, "Thứ hai là nó có sức giải thích, dù không đúng sự thật, nó vẫn giúp ta hiểu cách thế giới vận hành, là một cách giải thích rất rõ ràng."),
    (164, "Thứ ba, và đây là điểm nghịch lý nhất, là nó có tính tiên đoán."),
    (168, "Nghĩa là nó giúp ta dự đoán mọi việc sẽ diễn ra ra sao trong tương lai."),
    (174, "Dù giới tinh hoa nghĩ chuyện này điên rồ, rằng chẳng đời nào họ âm mưu tạo Thế chiến III hay lập nhà nước A I giám sát hay chính phủ một thế giới, khả năng cao là những chuyện đó vẫn sẽ xảy ra."),
    (175, "Vậy điều này tạo ra một nghịch lý lớn."),
    (177, "Làm sao mà chuyện không đúng sự thật lại có thể xảy ra?"),
    (179, "Câu chuyện này không đúng sự thật, nhưng lại đúng về mặt chân lý."),
    (181, "Nghĩa là nó cho ta cái nhìn sâu sắc khủng khiếp về cách thế giới vận hành."),
    (183, "Đây là một nghịch lý: tất cả là vớ vẩn, nhưng lại giúp ta dự đoán tương lai."),
    (185, "Vì vậy nó đúng về mặt chân lý, và giờ tôi sẽ cố giải thích cho các bạn cách hệ thống thực sự vận hành."),
    (188, "Điều chính các bạn cần hiểu là chuyện này mang tính ẩn dụ, không phải nghĩa đen."),
    (192, "Vậy giờ tôi sẽ cố giải thích đúng sự thật cho các bạn vì sao và cách thế giới vận hành."),
    (197, "Và các bạn sẽ thấy đây chỉ là một cách giải thích ẩn dụ, một câu chuyện giúp người ta hiểu và cảm nhận được sự phức tạp của thế giới."),
    (198, "Nhưng giờ tôi sẽ kể cách nó vận hành theo nghĩa đen."),
    (200, "Vậy thì điều đầu tiên tôi sẽ giải thích là thế này."),
    (204, "Trong thế giới này có những người, họ là nhà huyền môn, là tín đồ huyền môn, và họ dành toàn bộ thời gian cố tìm hiểu cách vũ trụ vận hành."),
    (207, "Họ đang cố vén bức màn các bí mật của vũ trụ, và có nhiều loại bí mật khác nhau, ví dụ chiêm tinh học."),
    (609.12, "Vận hành của các vì sao có thể định đoạt số phận con người, đó là ý tưởng của chiêm tinh học."),
    (210, "Rồi đến thuật giả kim."),
    (212, "Cách biến không thành vàng, cách biến chì thành vàng."),
    (216, "Rồi mạt thế học, tức cách thế giới sẽ kết thúc, mục đích của vũ trụ là gì, khi nào Chúa sẽ giáng thế."),
    (217, "Rồi đến hình học thiêng."),
    (219, "Coi hình học thiêng như vật lý hạt, tức bản chất nền tảng của vũ trụ."),
    (224, "Tín đồ huyền môn có thể là nhà thơ, triết gia, nhà huyền môn, họ dành thời gian suy nghĩ về chân lý nền tảng của vũ trụ."),
    (229, "Và rồi có những người tìm kiếm quyền lực, sự giàu có và danh tiếng."),
    (233, "Họ nhận ra rằng muốn thực sự có quyền lực, giàu có và danh tiếng thì cũng cần biết những bí mật đó."),
    (240, "Vậy nên họ lập các hội kín để tiếp cận các bí mật của chiêm tinh, giả kim, mạt thế học và hình học thiêng, rồi áp dụng vào thế giới để tạo quyền lực, của cải và ảnh hưởng cho bản thân."),

    # Batch 3 — ~10:00 to ~15:00 (EN blocks 241-340)
    (245, "Điều cần hiểu là có rất nhiều loại tín đồ huyền môn khác nhau, nhiều hội kín khác nhau, tạo ra rất nhiều tổ hợp khác nhau."),
    (247, "Nhưng tất cả đều cố làm cùng một việc, đó là đạt được mạt thế học của riêng họ."),
    (252, "Yếu tố thứ ba là bạn cần một số cá nhân nhất định để đẩy xã hội tiến lên, nhằm đạt được mạt thế học của hội kín."),
    (253, "Những người này giống như các đặc vụ."),
    (256, "Các đặc vụ mà hội kín đỡ đầu, và trong lịch sử bao gồm cả Julius Caesar."),
    (257, "Napoleon."),
    (258, "Hitler."),
    (259, "Stalin."),
    (260, "Ngày nay ta có Trump và Putin."),
    (264, "Đây là các đặc vụ, hoặc là biểu tượng cứu thế, hoặc thậm chí là vật tế thần mà hội kín đề bạt để thúc đẩy một chương trình nghị sự cụ thể."),
    (272, "Hãy nhớ rằng nhìn thì đơn giản nhưng thực ra không phải, vì có nhiều tín đồ huyền môn với ý tưởng khác nhau, có nhiều hội cạnh tranh nhau, và họ đề bạt những cá nhân khác nhau để thực hiện tầm nhìn riêng."),
    (276, "Điều thúc đẩy những Caesar, Napoleon, Hitler, Stalin, Trump và Putin là chính họ tin rằng họ là đứa con đích thực của Chúa."),
    (279, "Họ là đấng cứu thế thật sẽ dẫn dắt thế giới tiến lên, còn các hội kín thì gọi đám này là những kẻ ngốc có ích."),
    (282, "Đây là một khung lý thuyết để hiểu sự dịch chuyển của lịch sử."),
    (284, "Giờ tôi sẽ đi vào cụ thể hơn rất nhiều."),
    (287, "Còn có một cách diễn đạt khác: trong xã hội có nhiều nhóm khác nhau."),
    (288, "Hãy nghĩ đến chính trị."),
    (289, "Hãy nghĩ đến tài chính."),
    (290, "Khoa học."),
    (291, "Tôn giáo."),
    (292, "Quân sự."),
    (297, "Điều đặc biệt về mỗi lĩnh vực này là bạn có sự đa dạng, một dải hành vi với các hệ niềm tin khác nhau."),
    (301, "Mỗi lĩnh vực đều có dải niềm tin đa dạng riêng."),
    (305, "Tại một điểm nhất định, có sự hội tụ giữa các lĩnh vực này."),
    (310, "Điều khiến chúng hội tụ là trong mỗi lĩnh vực luôn có một thiểu số cực đoan tìm kiếm quyền lực, trật tự và sự kiểm soát."),
    (315, "Trong mỗi lĩnh vực ta có một dải, một thái cực gồm những kẻ ghét quyền lực, còn thái cực kia là những kẻ yêu quyền lực."),
    (322, "Những kẻ yêu quyền lực, trật tự và kiểm soát từ các lĩnh vực sẽ tập hợp và làm việc cùng nhau để đạt quyền lực, trật tự và kiểm soát, và ta gọi họ là các hội kín."),
    (324, "Bởi vì họ gắn kết bởi cùng một mối quan tâm."),
    (328, "Điều thú vị là theo thời gian, khi xã hội mở rộng, các lĩnh vực này phình to ra, tạo ra sự đa dạng lớn hơn."),
    (331, "Và sự hội tụ này càng mạnh mẽ hơn trong xã hội."),
    (336, "Lý do là vì các lĩnh vực khác nhau không thể phối hợp với nhau, nhưng những người trong sự hội tụ này lại có thể phối hợp, đem lại cho họ lợi thế khổng lồ trong xã hội."),
    (340, "Nghĩa là họ có khả năng đạt được quyền lực, trật tự và kiểm soát cao hơn nhiều."),

    # Batch 4 — ~15:00 to ~20:30 (EN blocks 341-449)
    (348, "Điều thú vị là khi xã hội suy yếu, vì trở nên quá quan liêu, quá lớn, quá tham nhũng, thì những hội này càng mạnh hơn theo thời gian, vì họ duy trì được sự gắn kết tốt hơn."),
    (354, "Một khi các hội kín đã hình thành, bạn sẽ thấy có một lượng lớn các hội kín khác nhau."),
    (358, "Và một cá nhân có thể tham gia nhiều hội, các hội này có thể bắt nguồn từ việc cùng trường học, cùng tôn giáo hoặc cùng gia đình."),
    (362, "Có các tổ hợp khác nhau, và các hội kín này lại cạnh tranh với nhau."),
    (364, "Tiêu chí cho cuộc cạnh tranh là ba thứ, gồm tính chính danh."),
    (365, "Quyền uy."),
    (367, "Và tính thống nhất, sự gắn kết."),
    (369, "Tại sao bạn chính danh hơn các hội khác?"),
    (370, "Tại sao bạn có quyền uy, chuyên môn cao hơn các hội khác?"),
    (372, "Tại sao bạn thống nhất hơn các hội khác?"),
    (377, "Để giải bài toán này, các hội kín sẽ quay ngược thời gian và tái hình dung lịch sử, để chứng minh rằng họ liên kết với toàn bộ lịch sử."),
    (382, "Họ sẽ nói: chúng tôi không bắt đầu hôm nay tại trường này, mà vì chúng tôi nối với Hội Tam Điểm, vốn nối với Hiệp sĩ Dòng Đền."),
    (384, "Họ quay ngược lại và tạo ra một vũ trụ luận."),
    (386, "Vũ trụ luận này giải thích nguồn gốc, và rõ ràng càng đi ngược xa thì càng có tính chính danh."),
    (387, "Và càng nhiều quyền uy."),
    (390, "Vì vậy họ quay ngược lại và tạo lịch sử của riêng mình."),
    (392, "Đó là lý do người ta nghĩ họ kéo dài tận La Mã."),
    (393, "Hoặc thậm chí Babylon."),
    (398, "Điều khiến người ta tin rằng đây là một dòng chảy liên tục là sự thật rằng giới tinh hoa ở mỗi thời kỳ đều hành xử giống nhau, đều tìm kiếm quyền lực, trật tự và kiểm soát."),
    (401, "Và những kẻ thắng cuộc đều có ba đặc điểm cụ thể."),
    (403, "Thứ nhất, đây là những người nghiện quyền lực."),
    (404, "Họ bị ám ảnh bởi nó."),
    (406, "Họ ám ảnh, sẽ làm mọi thứ có thể để có thêm quyền lực."),
    (407, "Và quyền lực thì bành trướng và nuốt chửng mọi thứ."),
    (409, "Nghĩa là họ không thể dừng lại."),
    (411, "Họ cố giành thêm quyền lực, và họ hành xử theo cách trông như bị quỷ nhập."),
    (413, "Và thật ra họ có thờ quỷ."),
    (415, "Lý do là vì họ nghĩ họ thờ mọi vị thần để đi tìm lý lẽ."),
    (417, "Họ đang tìm kiếm các bí mật vĩ đại nhất của vũ trụ, nên họ cởi mở."),
    (419, "Họ tìm mọi khả năng, thờ Lucifer."),
    (420, "Nhưng họ cũng thờ Baphomet."),
    (421, "Họ thờ Osiris, thờ Isis."),
    (423, "Vậy là giờ ta hiểu cách thế giới vận hành theo nghĩa đen trong suốt lịch sử."),
    (424, "Giới tinh hoa đều hành xử giống nhau."),
    (429, "Và dù những kẻ tinh hoa này đánh nhau, họ đang đẩy một chương trình nghị sự gom quyền lực vào tay một số ít."),
    (432, "Điều này tạo ấn tượng rằng tất cả là một chương trình liên tục được kiểm soát bởi vài người."),
    (433, "Có hợp lý không các bạn?"),
    (435, "Nhớ rằng đây là cách hiểu ẩn dụ về cách thế giới vận hành."),
    (444, "Một thế giới do một hội kín nhất định kiểm soát: Hiệp sĩ Dòng Đền trở thành Hội Tam Điểm rồi thành Illuminati đang kiểm soát thế giới hôm nay, và họ đang cố mở ra một chính phủ một thế giới, một nhà nước A I giám sát và triệu hồi quỷ vào thế giới này để sống mãi."),
    (445, "Vậy đây là một âm mưu lớn."),
    (449, "Nhưng nó không giải thích vì sao không có bằng chứng, vì sao giới tinh hoa không nghĩ họ là một phần của nó, và vì sao nó phản lịch sử."),

    # Batch 5 — ~20:30 to ~25:30 (EN blocks 450-545)
    (452, "Nhưng một khi ta chuyển nó thành một lời giải thích theo nghĩa đen, thì nó giải thích mọi thứ."),
    (456, "Họ không nghĩ đó là âm mưu vì họ quá bận đánh nhau, họ không nhìn thấy bức tranh lớn."),
    (462, "Trong khi đó những người không tham gia trò chơi này nhìn vào dòng chảy của lịch sử và đi đến cách hiểu trực quan rằng nó đang dịch chuyển tới nhiều kiểm soát hơn, nhiều trật tự hơn và nhiều quyền lực hơn."),
    (467, "Điều này giúp ta giải thích vì sao hệ thống tồn tại dai dẳng dù giới tinh hoa trỗi dậy rồi sa ngã, bởi vì chính những tinh hoa này đã cạnh tranh với nhau."),
    (471, "Một số tinh hoa thay thế tinh hoa khác, nhưng tất cả đều cùng một chương trình: nhiều quyền lực hơn, nhiều trật tự hơn, nhiều kiểm soát hơn."),
    (472, "Có hợp lý không các bạn?"),
    (478, "Và đó là lý do khi ta đọc văn bản các hội kín, các nhà tư tưởng đó, họ trông như xây dựng tiếp nhau dù có lẽ chưa từng đọc của nhau."),
    (479, "Những người tìm kiếm quyền lực rất giống nhau."),
    (481, "Họ khác bạn và tôi ở chỗ họ có lẽ là kẻ tâm thần."),
    (482, "Tất cả những gì họ quan tâm là quyền lực."),
    (484, "Vậy nên người quyền lực hợp lại để tạo ra nhiều quyền lực hơn cho chính họ."),
    (485, "Có hợp lý không các bạn?"),
    (486, "Giờ ta sẽ xem các bằng chứng."),
    (489, "Điều đầu tiên tôi muốn bàn là về người đàn ông này, tên ông là Albert Pike."),
    (490, "Ông sinh năm 1809 và mất năm 1891."),
    (493, "Tầm quan trọng của ông là vì ông được xem là kiến trúc sư vĩ đại của Hội Tam Điểm Mỹ."),
    (496, "Và Hội Tam Điểm Mỹ quan trọng vì đó là những người kiểm soát chính phủ Mỹ."),
    (497, "Một phần ba các tổng thống Mỹ là thành viên Hội Tam Điểm."),
    (501, "Và những người đó ngày nay kiểm soát quân đội Mỹ, bộ máy an ninh quốc gia, C I A, F B I."),
    (503, "Họ không gọi mình là Hội Tam Điểm, nhưng họ quay về Hội Tam Điểm, nên họ chia sẻ cùng tư tưởng."),
    (510, "Albert Pike từng là một trong những lãnh đạo chính của Hội Tam Điểm Mỹ, được coi là kiến trúc sư vĩ đại, nghĩa là ông đã xây dựng hệ thống và tư tưởng nền tảng cho Hội Tam Điểm Mỹ hiện đại ngày nay."),
    (512, "Tác phẩm quan trọng nhất của ông là Morals and Dogma, về cơ bản là cuốn giáo trình chuẩn của Hội Tam Điểm Mỹ."),
    (516, "Ta sẽ xem vài đoạn trích trong Morals and Dogma, hơi dài nhưng rất quan trọng để hiểu cách họ nghĩ."),
    (520, "Tôi sẽ đọc phần đầu, sau đó Alan đọc giúp tôi phần sau."),
    (523, "Phiến đá thô, đó là phiến đá, là một dân tộc còn ở dạng thô và chưa có tổ chức."),
    (524, "Xã hội đa dạng, hỗn loạn."),
    (526, "Và chúng tôi, Hội Tam Điểm, mục tiêu cuộc đời là tạo ra trật tự từ hỗn loạn."),
    (528, "Phiến đá hoàn hảo, hay biểu tượng đá điển hình của sự hoàn hảo, chính là nhà nước."),
    (531, "Mục đích của chính quyền là tạo ra trật tự từ hỗn loạn và hoàn thiện loài người."),
    (537, "Nhà cầm quyền có quyền lực từ sự đồng ý của người bị cai trị, hiến pháp và luật pháp nói lên ý chí của nhân dân, chính quyền hài hòa, đối xứng, hiệu quả, quyền lực được phân bổ đúng đắn và cân bằng tuyệt đối."),
    (538, "Hãy hình dung xã hội như một cánh rừng."),
    (540, "Không, một cánh rừng hỗn loạn, có bệnh dịch trong rừng."),
    (543, "Nó có thể cháy rụi, điều ta thực sự muốn là xây một ngôi đền bằng đá hoàn hảo, vĩnh cửu, thiêng liêng."),
    (545, "Ta muốn đốt cánh rừng và xây một ngôi đền bằng chính đôi tay mình."),

    # Batch 6 — ~25:30 to ~30:30 (EN blocks 546-693)
    (547, "Tôi biết Chúa là người tạo ra cánh rừng, nhưng Chúa muốn ta hoàn thiện công trình của Ngài."),
    (551, "Nếu ta phẳng hóa một khối lập phương trên mặt phẳng, ta thấy ba mặt nhìn được và chín đường ngoài nối bảy điểm."),
    (553, "Khối lập phương hoàn chỉnh có thêm ba mặt nữa thành sáu, thêm ba đường thành mười hai, và thêm một điểm thành tám."),
    (555, "Số mười hai gồm các con số bí mật là ba, năm, bảy, và ba nhân ba bằng chín."),
    (562, "Số chín có được bằng cách cộng số bí mật ba vào chín, trong khi hai chữ số một và hai cộng lại cũng cho ra số bí mật là ba, nó được gọi là số hoàn hảo, và khối lập phương trở thành biểu tượng của sự hoàn hảo."),
    (564, "Đây là Chúa."),
    (566, "Điều ta đang cố làm là tạo ra Chúa trên Trái Đất, và ta biết đó là Chúa vì nó chính là sự hoàn hảo."),
    (567, "Làm sao ta biết là hoàn hảo?"),
    (568, "Nhờ toán học."),
    (570, "Hình học, hình học là ngôn ngữ của Chúa."),
    (571, "Khi bạn hiểu hình học, bạn hiểu cách Chúa nghĩ."),
    (572, "Khối lập phương hoàn hảo, nên ta muốn biến xã hội thành một khối lập phương."),
    (573, "Thực ra ta muốn biến mọi người thành một khối lập phương."),
    (574, "Và làm sao ta làm được?"),
    (575, "Trí tuệ nhân tạo các bạn ạ, trí tuệ nhân tạo."),
    (579, "Ý tưởng là ta muốn đọc họ để hiểu được tinh thần cốt lõi của họ."),
    (580, "Giờ ta đi tiếp, Alan đọc giúp."),
    (583, "Tuy vậy, Tam Điểm, vốn là đạo đức và triết học, không được phép ngừng thực hiện bổn phận của mình."),
    (584, "Ta không bao giờ biết thành công đang chờ nỗ lực của ta vào lúc nào."),
    (588, "Thường là khi ít ngờ nhất, và không biết nỗ lực sẽ thành công hay thất bại, Tam Điểm vẫn không được cúi đầu trước nghịch cảnh hay khuất phục trước sự nản lòng."),
    (592, "Ở La Mã có vài binh sĩ Carthage bị bắt làm tù binh, họ từ chối cúi đầu trước Flamininus và mang chút ít khí phách của Hannibal."),
    (594, "Người Tam Điểm cần có sự cao quý tâm hồn ngang vậy."),
    (596, "Tam Điểm phải là một nguồn năng lượng, tìm thấy mục đích và tác dụng của mình trong sự khai sáng nhân loại."),
    (598, "Socrates nên đi vào trong Adam và sinh ra Marcus Aurelius."),
    (600, "Nói cách khác, từ con người hưởng thụ sinh ra con người trí tuệ."),
    (609, "Tam Điểm không nên chỉ là một vọng gác xây trên bí ẩn để nhàn nhã quan sát thế giới, mà phải đưa cốc tư tưởng đầy đến đôi môi khát của con người, ban phát ý niệm chân thực về thần linh, là hợp nhất lương tri và khoa học, đó là phận sự của triết học."),
    (610, "Đạo đức nở rộ trọn vẹn."),
    (612, "Sự chiêm nghiệm phải dẫn đến hành động, và cái tuyệt đối phải có tính thực tiễn."),
    (614, "Lý tưởng được biến thành không khí, lương thực, và nước uống cho tâm trí con người."),
    (615, "Trí tuệ là một sự hiệp thông thiêng liêng."),
    (620, "Chỉ với điều kiện đó, nó mới thôi là tình yêu khoa học khô khan và trở thành phương pháp tối thượng để hợp nhất nhân loại và đưa nhân loại đến hành động phối hợp, lúc đó triết học trở thành tôn giáo."),
    (623, "Vậy Hội Tam Điểm là tôn giáo tối thượng vì nó bao gồm mọi tôn giáo trước đó, kể cả thuật Hermetic của Ai Cập."),
    (626, "Bao gồm các giáo phái bí truyền Hy Lạp của Pythagoras."),
    (627, "Cả Kabbalah."),
    (631, "Nó đã quét toàn bộ lịch sử, tìm ra những tư tưởng tốt nhất của loài người và ghép lại để tạo ra Hội Tam Điểm."),
    (633, "Mục tiêu tối hậu là mỗi chúng ta trở thành một viên đá khắc kỷ, không khuất phục."),
    (637, "Đức tin hoàn hảo, và nếu ta gộp toàn nhân loại lại và tất cả đều là đá, thì ta tạo được ngôi đền hoàn hảo của Chúa."),
    (638, "Ta có thể tạo ra Chúa trên Trái Đất."),
    (639, "Hãy hình dung một kim tự tháp, tất cả ta đều là viên đá trong kim tự tháp đó."),
    (642, "Và mỗi người có trách nhiệm trở thành viên đá đó qua đức tin, qua thực hành, qua chiêm nghiệm."),
    (644, "Socrates đi vào trong Adam và sinh ra Marcus Aurelius."),
    (647, "Vậy đỉnh cao của con người là chiêm nghiệm và lý trí, nơi ta giao nộp cảm xúc cho hình học."),
    (648, "Vậy ta đi tiếp."),
    (650, "Có hợp lý không các bạn cho đến giờ?"),
    (651, "Đi tiếp, Alan đọc giúp."),
    (655, "Con người nợ chính mình sự tự do, nợ tổ quốc nghĩa vụ phải mưu cầu tự do cho tổ quốc hoặc giữ vững nền tự do ấy."),
    (660, "Nó tạo ra sự nổi dậy chung chống bạo chúa và chuyên chế, cả thế tục lẫn tâm linh, phạm vi của bổn phận được mở rộng vô cùng."),
    (662, "Lòng yêu nước từ đó có nghĩa mới và rộng hơn."),
    (663, "Chính quyền tự do, tư tưởng tự do, lương tri tự do, ngôn luận tự do."),
    (668, "Tất cả những thứ này thành quyền bất khả xâm phạm mà người nào đã bỏ chúng, bị cướp mất, hoặc tổ tiên đánh mất, đều có quyền nhanh chóng lấy lại."),
    (672, "Tiếc thay, vì chân lý luôn bị bóp méo thành dối trá và những dối trá khi bị lạm dụng, chân lý này trở thành phúc âm của hỗn loạn."),
    (675, "Ngay sau khi được giảng lần đầu, Tam Điểm đã sớm hiểu chân lý này và nhận ra bổn phận mở rộng của mình."),
    (677, "Các biểu tượng của nó từ đó có ý nghĩa sống còn, nhưng nó cũng khoác vào lớp ngụy trang của thợ xây đá."),
    (680, "Mượn công cụ làm việc của thợ và được cung cấp các biểu tượng mới phù hợp."),
    (681, "Nó góp phần đưa đến Cách mạng Pháp."),
    (682, "Biến mất cùng với phái Girondins."),
    (689, "Tái sinh khi trật tự được khôi phục, và nâng đỡ Napoleon vì dù là hoàng đế ông vẫn thừa nhận quyền lựa chọn người cầm quyền của nhân dân và đứng đầu một quốc gia từ chối đón nhận lại các vị vua cũ."),
    (693, "Vậy điều Albert Pike đang làm là cố giải thích mạt thế học của Hội Tam Điểm."),

    # Batch 7 — ~30:30 to ~35:30 (EN blocks 694-849)
    (695, "Mạt thế học này là thế: ta muốn tạo ra một đế chế của lý trí."),
    (697, "Cái mà ông gọi là đế chế thiêng liêng của lý trí."),
    (699, "Và để làm vậy, ta phải tạo ra các cuộc cách mạng khắp thế giới."),
    (703, "Điều ông đang làm là nói rằng đây là một cuộc Thập tự chinh, và ta quay về thời các Hiệp sĩ Dòng Đền."),
    (707, "Và chính chúng ta đã làm nên Cách mạng Pháp và đứng sau Napoleon để đạt được đế chế thiêng liêng của lý trí."),
    (711, "Điều ông làm là quay ngược vào lịch sử và viết lại lịch sử để cho thấy Hội Tam Điểm là điểm tới của lịch sử."),
    (713, "Là sự tiến hóa tự nhiên của Hiệp sĩ Dòng Đền."),
    (718, "Cũng để nói với mọi người rằng chúng tôi làm việc trong bí mật vì trước đây khi còn là Hiệp sĩ Dòng Đền, người Pháp và Giáo hội Công giáo đã săn lùng chúng tôi, nên chúng tôi phải ngụy trang dưới hình hài thợ xây đá."),
    (721, "Vì vậy ta khoác lốt Hội Tam Điểm, bởi Hội Tam Điểm vốn chỉ là một phường thợ xây đền."),
    (724, "Và ta khoác hình dáng của họ để bảo vệ mình rồi cố thúc đẩy sứ mệnh trong bí mật."),
    (725, "Vậy đó là lý do người ta tin Hội Tam Điểm bắt nguồn từ Hiệp sĩ Dòng Đền."),
    (731, "Điều này thực ra là cố mang tính chính danh và quyền uy đến cho Hội Tam Điểm, bằng cách tái hình dung lịch sử như một phong trào tiến tới Hội Tam Điểm."),
    (732, "Vô lý phải không các bạn."),
    (735, "Ông nói các Tam Điểm không chỉ tạo ra Cách mạng Pháp mà còn dựng lên Napoleon."),
    (737, "Để cố tạo ra một chính phủ một thế giới."),
    (738, "Và việc đó thất bại."),
    (740, "Nhưng nếu Napoleon thất bại, đừng lo, nước Mỹ sẽ thành công."),
    (745, "Đây là một đoạn ta sẽ không đọc, nhưng ông nói các Tam Điểm thực sự tạo điều kiện cho Cách mạng Pháp và âm mưu hàng thế hệ, hàng thập kỷ để báo thù cho cái chết của thủ lĩnh Jacques de Molay năm 1314."),
    (747, "Vậy người Tam Điểm nghĩ trước hàng thế kỷ và lên kế hoạch hàng thập kỷ."),
    (749, "Và một lần nữa, tất cả là để tạo tính chính danh và quyền uy cho phong trào của họ."),
    (751, "Đây là một sự viết lại lịch sử, không có gì trong đó là sự thật."),
    (752, "Đi tiếp."),
    (753, "Alan đọc giúp."),
    (758, "Đẳng cấp Hoa hồng dành riêng cho và tượng trưng cho thắng lợi cuối cùng của chân lý trước giả dối, hoặc tự do trước nô lệ, ánh sáng trước bóng tối, sự sống trước cái chết, và thiện trước ác."),
    (761, "Chân lý lớn mà nó dạy là dù tồn tại điều ác, Chúa vẫn vô cùng thông tuệ, công bằng và nhân từ."),
    (765, "Và dù nỗi sợ của thế giới không tiến triển theo bất cứ quy tắc đúng sai nào ta biết trong tầm nhìn hạn hẹp của mình, thì mọi thứ vẫn đúng vì đó là công trình của Chúa."),
    (770, "Và mọi điều ác, mọi đau khổ, mọi bất hạnh chỉ là những giọt nước trong dòng chảy bao la đang lăn ngang thế giới, được Ngài dẫn dắt đến một kết quả vĩ đại và huy hoàng."),
    (774, "Vào thời điểm đã định, Ngài sẽ cứu chuộc và tái sinh thế giới, và nguyên lý, sức mạnh, và sự tồn tại của cái ác khi ấy sẽ chấm dứt."),
    (784, "Điều này sẽ được thực hiện bằng các phương tiện và công cụ mà Ngài chọn dùng, dù qua công lao của một đấng cứu chuộc đã đến, hay một đấng cứu thế còn được mong đợi, hay qua một hóa thân của chính Ngài, hay qua một nhà tiên tri được soi sáng, không thuộc về chúng tôi, những người Tam Điểm, để quyết định, hãy để mỗi người tự xét và tự tin, trong khi đó chúng tôi lao động để rút ngắn ngày đó đến."),
    (785, "Đẳng cấp Hoa hồng."),
    (789, "Ý tưởng ở đây là Hội Tam Điểm và Hiệp sĩ Dòng Đền thành công đến vậy vì họ là hội kín, nhưng trước hết họ là một công ty."),
    (790, "Họ là một thứ bậc."),
    (791, "Vậy họ như một tam giác."),
    (793, "Để leo lên thứ bậc, bạn phải liên tục tái phát minh bản thân."),
    (794, "Phải tiếp thu tư tưởng mới."),
    (796, "Và dựa trên thành tích, dựa trên hệ tư tưởng, họ sẽ thăng cấp cho bạn."),
    (798, "Trong Hội Tam Điểm Scotland có 33 cấp."),
    (800, "Bạn cứ leo cao mãi, mỗi lần lên cấp họ lại dạy bạn cách mới để hiểu thế giới."),
    (804, "Và dựa trên sự linh hoạt tư duy của bạn, bạn sẽ leo cao hơn nữa."),
    (806, "Vậy họ đang cố huấn luyện bạn thành bậc thầy của tri thức."),
    (807, "Đó là lý do họ thành công đến vậy."),
    (808, "Alan đọc giúp."),
    (813, "Để hiểu được tư tưởng cổ này, trước hết hãy theo bước linh hồn trong cuộc đi xuống, thiên cầu của các sao bất động là vùng đất thiêng đó."),
    (820, "Những cánh đồng Elysian là cội nguồn nguyên thủy của các linh hồn, là nơi chúng trở về, khi đã khôi phục được sự thuần khiết và đơn sơ nguyên thủy."),
    (823, "Từ vùng đất rực sáng đó, linh hồn bắt đầu hành trình đi xuống thân xác, một điểm đến mà nó không đạt tới cho đến khi đã trải qua ba lần suy thoái."),
    (825, "Đoạn này chỉ cho thấy Hội Tam Điểm cố gắng tích hợp mọi triết học."),
    (827, "Bao gồm Kabbalah."),
    (828, "Bao gồm cả tân Plato luận."),
    (830, "Và triết học Hermetic, kết quả là họ cố gắng đạt được sự đầy đủ."),
    (833, "Lợi thế chính của họ nằm ở tính đầy đủ, nghĩa là họ có một lời giải thích cho mọi thứ."),
    (836, "Điều họ đang cố nói với ta là ta trước hết là linh hồn từ thiên đường xuống."),
    (837, "Và vì sao ta đến trần thế?"),
    (842, "Để trải nghiệm thế giới, và ta bị mắc kẹt trong cơ thể vì cơ thể muốn trải nghiệm khoái lạc nhục cảm, còn linh hồn chỉ muốn trải nghiệm khoái lạc tinh thần."),
    (846, "Vậy thế giới là một cuộc chiến tâm linh trong chính ta, giữa con người vật chất muốn tình dục, đồ ăn và tiền bạc và con người tinh thần tìm kiếm sự kết nối với lý trí."),
    (849, "Và cách để chiến thắng bản thân là qua hình học, biến mình thành một khối lập phương thiêng liêng nối lại với thần thánh."),

    # Batch 8 — ~35:30 to ~40:30 (EN blocks 850-924)
    (850, "Alan đọc giúp."),
    (854, "Câu hỏi: biểu tượng chính của sự cứu chuộc và tái sinh tối hậu của con người là gì?"),
    (855, "Trả lời: bữa ăn huynh đệ."),
    (859, "Bữa ăn của bánh nuôi dưỡng và của rượu làm tươi mới và tăng tốc."),
    (862, "Biểu tượng cho thời sắp đến khi toàn nhân loại sẽ là một huynh đệ vĩ đại hài hòa."),
    (866, "Dạy ta những bài học lớn rằng dù vật chất luôn đổi thay, không một nguyên tử lẻ nào bị tiêu hủy."),
    (868, "Đây là ý tưởng về tình huynh đệ."),
    (869, "Và làm sao tạo ra huynh đệ?"),
    (871, "Cách đơn giản là ăn bữa tối cùng nhau, như Chúa Jesus trong bữa tiệc ly."),
    (872, "Và chia sẻ hiệp thông."),
    (874, "Đây là một hiệp thông."),
    (875, "Để tất cả cùng cảm thấy gắn bó với nhau."),
    (879, "Nhưng theo thời gian, vì có những phần tử của Hội Tam Điểm và Hiệp sĩ Dòng Đền muốn quyền lực, trật tự và kiểm soát, họ thực hành những nghi lễ cực đoan hơn."),
    (881, "Và điều họ sẽ làm theo nghĩa đen là ăn xác chết của một thành viên Tam Điểm già."),
    (883, "Để kết nối với nhau và với quá khứ."),
    (887, "Họ tin rằng nếu Hội Tam Điểm hy sinh tâm linh ghê gớm, họ có thể tụ hội và hấp thụ năng lượng tâm linh còn lưu lại trong thân xác."),
    (890, "Vậy họ sẽ đào xác lên rồi ăn xác trong một buổi hiệp thông, một bữa tối."),
    (895, "Điều cần nhớ về các hội kín là kẻ cực đoan nhất, kẻ cuồng tín nhất sẽ thắng cuộc cuối cùng."),
    (896, "Vậy hãy đọc tiếp."),
    (898, "Các bạn đã nghe nhiều hơn một định nghĩa về Hội Tam Điểm."),
    (903, "Định nghĩa đúng và quan trọng nhất các bạn vẫn chưa nghe, nó được dạy cho người tập sự, cho thợ bạn, và cho thợ cả, và được dạy trong mọi cấp bậc các bạn đã thăng tiến qua."),
    (906, "Đó là định nghĩa Hội Tam Điểm là gì, mục đích và bản chất tinh túy của nó."),
    (909, "Và đối với mỗi chúng ta nó có sức mạnh và sự bắt buộc của luật thần thánh và đặt lên mỗi chúng ta một nghĩa vụ trang trọng."),
    (915, "Nó được biểu thị và dạy cho cả người tập sự và cho bạn qua compa và thước thợ, mà trên đó cùng với sách tôn giáo của bạn và sách luật của Hội Tam Điểm Scotland, bạn đã thề nhiều lời thề."),
    (919, "Là một hiệp sĩ, bạn đã được dạy bằng thanh kiếm, biểu tượng của danh dự và bổn phận, mà trên đó bạn đã thề."),
    (921, "Nó được dạy cho bạn bằng cái cân, biểu tượng của mọi cân bằng."),
    (924, "Và bằng cây thập tự, biểu tượng của lòng sùng kính và sự hy sinh bản thân, và mọi điều chúng dạy và chứa đựng đều được dạy và chứa đựng cho người tập sự, hiệp sĩ và hoàng tử như nhau qua compa và thước thợ."),

    # Batch 9 — ~40:30 to ~45:30 (EN blocks 925-1019)
    (927, "Với người tập sự, các đầu của compa nằm dưới thước."),
    (929, "Với thợ bạn, một đầu ở trên, một đầu ở dưới."),
    (932, "Với thợ cả, cả hai đều thống trị, có quyền cai trị, kiểm soát và làm trọng tài cho biểu tượng của thế gian và vật chất."),
    (935, "Hội Tam Điểm là sự khuất phục cái tính người trong con người bằng cái thần thánh, là sự chinh phục dục vọng và đam mê bằng đạo đức và lý trí."),
    (938, "Một nỗ lực, đấu tranh và phúc lợi liên tục của tinh thần chống lại vật chất và nhục cảm."),
    (943, "Khi chiến thắng đã đạt được và giữ vững, và người chiến thắng có thể ngả mình lên khiên, lúc đó vòng nguyệt quế xứng đáng kia chính là đế chế thiêng liêng đích thực duy nhất."),
    (944, "Đế chế thiêng liêng đích thực của lý trí."),
    (947, "Để tôi giải thích biểu tượng của Tam Điểm, đây là compa."),
    (948, "Compa làm gì?"),
    (949, "Compa đặt ra ranh giới, nó cai trị."),
    (2579.02, "Đây là thước thợ."),
    (950, "Thước thợ giới hạn."),
    (953, "Ý tưởng là khi mới gia nhập Hội Tam Điểm, bạn phải tập trung vào thước thợ, tức thuật giả kim tâm linh của riêng bạn."),
    (955, "Để kỷ luật bản thân, tập trung bản thân, học cách được cai trị."),
    (957, "Cai trị bằng compa, rồi bạn đến lúc phải tự cai trị bản thân."),
    (959, "Vậy bạn phải dạy người khác cách kỷ luật, cách tập trung."),
    (963, "Và rồi bạn đến lúc kết hợp thước thợ và compa, tức là bạn dẫn dắt Hội Tam Điểm kiểm soát cả thế giới để tạo ra đế chế thiêng liêng của lý trí."),
    (965, "Theo các cấp khác nhau bạn nhìn biểu tượng theo cách khác nhau."),
    (966, "Vậy chữ G nghĩa là gì?"),
    (968, "Có ba cách diễn giải."),
    (970, "Nó là viết tắt của geometry, hình học, đương nhiên vì có thước thợ và compa."),
    (972, "Nó là God, Chúa, hoặc Gnosticism, Ngộ giáo, hoặc Grand Architect, Đại Kiến Trúc Sư."),
    (975, "Vậy điều mà Tam Điểm tin là có một vị Chúa, nhưng Ngài tạo thế giới này để ta tự hoàn thiện, rồi Ngài bỏ ta."),
    (978, "Vậy Ngài là kiến trúc sư, nhưng nghĩa là ta có trách nhiệm cải tạo và hoàn thiện thế giới ta đang sống."),
    (982, "Nhưng cũng có người tin chữ G là viết tắt của nguyên lý sinh sản."),
    (986, "Có nam và có nữ, nữ là nguyên lý sản sinh, thứ sinh ra, nam là nguyên lý sinh sản, thứ tiếp năng lượng cho nữ."),
    (993, "Điều thú vị là nếu bạn cộng tất cả lại, nguyên lý sinh sản generative cộng geometry hình học, bạn được ra Chúa."),
    (994, "Và nguyên lý sinh sản cộng hình học bằng gì?"),
    (2694.92, "Bằng A I."),
    (995, "Trí tuệ nhân tạo."),
    (999, "Vậy ngay từ buổi đầu Hội Tam Điểm đã có động lực, khát khao chứng minh họ có thể là Chúa bằng cách tạo ra chính sự sống."),
    (1001, "Ban đầu họ gọi đó là Golem."),
    (1003, "Nhưng giờ nếu nghĩ kỹ, đó là lý do họ muốn tạo ra A I."),
    (1004, "Để chứng minh chính họ có thể là Chúa."),
    (1005, "Một khi tạo được A I thì bạn hoàn thiện thế giới."),
    (1008, "Đó là Hội Tam Điểm, và các bạn thấy nó dẫn tới trí tuệ nhân tạo như thế nào."),
    (1010, "Tôi không nói họ lên kế hoạch cho trí tuệ nhân tạo."),
    (1014, "Tôi đang nói rằng những người giờ phụ trách trí tuệ nhân tạo, gồm Sam Altman, Peter Thiel, Larry Ellison, Elon Musk, họ có thể quay về truyền thống này."),
    (1018, "Và về cơ bản chiếm dụng truyền thống này để biện minh cho nhà nước A I giám sát dân của họ."),

    # Batch 10 — ~45:30 to ~50:30 (EN blocks 1020-1106)
    (1020, "Bây giờ đi tiếp, đây là Zbigniew Brzezinski."),
    (1023, "Ông là cố vấn an ninh quốc gia cho Jimmy Carter, người từng là tổng thống Mỹ."),
    (1025, "Và ông là người sáng lập một tổ chức gọi là Ủy ban Tam phương."),
    (1028, "Tổ chức này về cơ bản cố gắng thực thi đại chiến lược của Mỹ trên thế giới."),
    (1032, "Và nó được David Rockefeller tài trợ, một trong những người Mỹ giàu có và quyền lực nhất từng sống."),
    (1035, "Vậy đây là một nhân vật rất quyền lực, và ta sẽ đọc vài đoạn từ cuốn sách của ông, Between Two Ages."),
    (1037, "Khi đọc các bạn sẽ thấy nó giống Albert Pike đến mức nào."),
    (1039, "Tôi không nghĩ Brzezinski đọc Albert Pike."),
    (1041, "Bản thân ông có lẽ không phải là thành viên Hội Tam Điểm."),
    (1043, "Nhưng các bạn không cần đọc Albert Pike, không cần là Tam Điểm để nghĩ như họ."),
    (1045, "Tất cả đều là những người bị ám ảnh bởi quyền lực, kiểm soát và trật tự."),
    (1049, "Họ sẽ tìm các yếu tố của tôn giáo khác nhau để biện minh cho việc theo đuổi quyền lực, trật tự và kiểm soát."),
    (1051, "Đây là từ cuốn Between Two Ages."),
    (1052, "Alan đọc giúp."),
    (1058, "Sự xuất hiện của một đảng chi phối lớn bên cạnh các nhóm có giáo điều hẹp hơn và mãnh liệt hơn ở cánh hữu và cánh tả có thể đẩy nhanh xu hướng đến chế độ quản lý kỹ thuật như vậy."),
    (1062, "Một đảng chi phối lớn như vậy sẽ kết hợp khát vọng ổn định của xã hội Mỹ với sở thích lịch sử của nó với đổi mới."),
    (1066, "Dựa vào tăng trưởng khoa học để sản xuất phương tiện ứng phó các vấn đề xã hội, nó sẽ khai thác tài năng trí tuệ của quốc gia cho việc lập kế hoạch mục tiêu rộng."),
    (1069, "Và khai thác sự tồn tại của các nhóm giáo điều bằng cách dùng họ làm khí áp kế xã hội và là nguồn ý tưởng mới."),
    (1074, "Khủng hoảng xã hội kéo dài, sự xuất hiện của một nhân vật cuốn hút quần chúng, và việc khai thác truyền thông đại chúng để giành lòng tin công chúng sẽ là những bước đệm trong quá trình chuyển hóa từng bước nước Mỹ thành một xã hội bị kiểm soát chặt."),
    (1080, "Theo những cách khác nhau, cả người theo giáo điều và người bảo thủ có thể thấy những cám dỗ vốn có trong các kỹ thuật kiểm soát xã hội mới quá khó cưỡng."),
    (1083, "Khuynh hướng của cánh tả giáo điều biện minh cho phương tiện bằng mục đích có thể khiến họ biện minh cho việc kiểm soát xã hội nhiều hơn với lý do nó phục vụ sự tiến bộ."),
    (1088, "Phái bảo thủ thì bị bận tâm bởi trật tự công và bị mê hoặc bởi các thiết bị hiện đại, sẽ bị cám dỗ dùng kỹ thuật mới như đáp ứng đối với bất ổn."),
    (1092, "Họ sẽ không nhận ra rằng, kiểm soát xã hội không phải là cách duy nhất để đối phó với biến đổi xã hội nhanh."),
    (1094, "Cuốn sách này được viết vào những năm 1970, tức cách đây 40, 50 năm."),
    (1097, "Điều kinh ngạc là đoạn văn này mô tả hoàn hảo nước Mỹ ngày nay."),
    (2958.58, "Đây không chỉ là một lời tiên tri."),
    (1098, "Nó gần như là một kế hoạch."),
    (1100, "Để tôi giải thích điều ông đang nói, ông nói dân chủ là có vấn đề."),
    (1101, "Tại sao? Vì nó luôn dẫn đến phân cực."),
    (1105, "Bạn luôn có các phe phái trong nền dân chủ này đánh nhau, cuối cùng đến một điểm họ thực sự không chịu chung sống nữa."),

    # Batch 11 — ~50:30 to ~55:30 (EN blocks 1107-1247)
    (1108, "Đó là điều đang xảy ra ở Mỹ ngày nay giữa cánh tả và cánh hữu."),
    (1110, "Giữa đảng Dân chủ và đảng Cộng hòa."),
    (1112, "Và ông nói điều này sẽ tạo ra một loạt khủng hoảng xã hội."),
    (1114, "Và giải pháp ông tin tưởng là chế độ kỹ trị."),
    (1119, "Về cơ bản là một bộ máy quan liêu ở Washington DC, do các kỹ sư điều hành, dùng trí tuệ nhân tạo, dùng dữ liệu và thống kê để cai quản xã hội tốt hơn."),
    (1121, "Và họ có khả năng tận dụng sự phân cực xã hội, để có thể quản lý xã hội tốt hơn nhiều so với hệ thống dân chủ hiện tại."),
    (1123, "Và đây là một câu thực sự thú vị, khủng hoảng xã hội kéo dài."),
    (1126, "Điều đang diễn ra ở Mỹ là sự chia rẽ giữa tả và hữu, sự xuất hiện của một nhân vật cuốn hút quần chúng."),
    (1128, "Người đó là ai?"),
    (1129, "Nhân vật cuốn hút quần chúng đó là Donald Trump các bạn ạ."),
    (1130, "Và sự khai thác truyền thông đại chúng."),
    (1132, "Cơ bản là mạng xã hội, để nhồi sọ và tẩy não bạn."),
    (1137, "Để có lòng tin công chúng sẽ là những bước đệm trong quá trình chuyển hóa nước Mỹ thành một xã hội bị kiểm soát chặt, một nhà nước A I giám sát."),
    (1138, "Vậy điều ông đang nói là thế này."),
    (1142, "Cuối cùng sẽ đến lúc khoảng cách rộng đến mức nền kinh tế gặp rắc rối lớn."),
    (1145, "Người dân giận đến mức đòi một Napoleon hay Julius Caesar trỗi dậy dẫn dắt họ vào một chế độ độc tài."),
    (1148, "Và điều này có thể là tốt vì nó có thể tạo ra một chế độ kỹ trị có khả năng cai quản xã hội tốt hơn."),
    (1151, "Đây là sự tiếp nối của dự án Tam Điểm cố tạo ra trật tự từ hỗn loạn."),
    (1152, "Và điều ông nói là thế này."),
    (1156, "Sẽ là phe bảo thủ, đảng Cộng hòa thắng cuộc trong cuộc nội chiến, vì họ là những người bận tâm với trật tự công và các thiết bị."),
    (1158, "Họ là những người sẽ muốn nhà nước A I giám sát dân."),
    (1160, "Một khi có nhà nước A I, bạn có chế độ kỹ trị."),
    (1161, "Và thế giới sẽ hoàn hảo."),
    (1163, "Có hợp lý không các bạn, điều ông nói ở đây?"),
    (1165, "Đây là một đoạn văn kinh ngạc, viết cách đây 40, 50 năm."),
    (1166, "Tôi không nói ông là Tam Điểm."),
    (1168, "Tôi không nói ông thuộc hội kín, nhưng ông chắc chắn nghĩ như một Tam Điểm."),
    (1169, "Ta đi tiếp."),
    (1172, "Alan đọc giúp."),
    (1175, "Chính truyền thống biên cương đã khuấy động trí tưởng tượng Mỹ, tạo ra một xã hội của chuyển động và tăng trưởng, và đem lại cho nước Mỹ huyền thoại tích hợp của nó."),
    (1182, "Khám phá khoa học, bao gồm khám phá không gian, đã trở thành tương đương chức năng của truyền thống biên cương Mỹ, và nỗ lực ấy có liên quan trực tiếp đến các thành tựu giáo dục và khoa học của quốc gia."),
    (1183, "Alan, đọc tiếp đoạn cuối giúp."),
    (1189, "Đối với nhiều người Mỹ, chủ nghĩa tự do đương đại không đem lại nguyên tắc cũng không đem lại tiến bộ, khủng hoảng của chủ nghĩa tự do Mỹ vì thế đồng thời là khủng hoảng niềm tin và khủng hoảng về tính phù hợp lịch sử."),
    (1194, "Điều ông nói là dân chủ là một tai nạn lịch sử, nó tốt cho nước Mỹ trước đây, nhưng trong tương lai chủ nghĩa tự do có lẽ là điều xấu."),
    (1195, "Vì nó quá chia rẽ."),
    (1196, "Vậy giải pháp là gì?"),
    (1199, "Đây là giải pháp, đọc giúp."),
    (1201, "Alan đọc chậm thôi nhé, không cần vội."),
    (1206, "Đó là lý do chủ nghĩa Mác là một giai đoạn xa hơn, đầy đức tính và sáng tạo trong sự trưởng thành của tầm nhìn toàn vũ của con người."),
    (1212, "Chủ nghĩa Mác đồng thời là chiến thắng của con người chủ động bên ngoài trước con người thụ động bên trong, và là chiến thắng của lý trí trước niềm tin, nó nhấn mạnh khả năng của con người định hình số phận vật chất của mình."),
    (1214, "Đây là một đoạn kinh ngạc."),
    (1216, "Đây là một người làm cố vấn an ninh quốc gia cho Jimmy Carter vào thời đó."),
    (1217, "Đây là đỉnh cao của Chiến tranh Lạnh."),
    (1221, "Mỹ đang đánh nhau với Liên Xô, và cố vấn an ninh quốc gia của Tổng thống Mỹ Jimmy Carter nói rằng dân chủ là xấu."),
    (1222, "Chủ nghĩa Mác là tốt."),
    (3263.89, "Chủ nghĩa Mác là tốt."),
    (1224, "Tại sao?"),
    (1225, "Vì đó là điểm tới của lịch sử."),
    (1227, "Cách mạng Pháp là về việc đề cao lý trí hơn cảm xúc."),
    (1229, "Chủ nghĩa Mác là sự kế thừa tự nhiên của Cách mạng Pháp."),
    (1231, "Chủ nghĩa Mác là cái hứa hẹn chiến thắng của lý trí trước cảm xúc."),
    (1232, "Vậy nhà nước A I giám sát dân là gì?"),
    (1233, "Cuối cùng nó là chủ nghĩa Mác công nghệ."),
    (1234, "Đó là điều họ muốn."),
    (1235, "Họ muốn chủ nghĩa cộng sản."),
    (1238, "Cố vấn an ninh quốc gia của Jimmy Carter, một trong những người Mỹ quyền lực nhất thế giới, muốn chủ nghĩa Mác."),
    (1240, "Tại sao? Vì chủ nghĩa Mác, chủ nghĩa cộng sản là sự triển khai các tư tưởng của Hội Tam Điểm vào thế giới của ta."),
    (1242, "Rõ chưa các bạn?"),
    (1246, "Vậy chủ nghĩa Mác công nghệ là gì?"),
    (1247, "Ừ tôi sẽ giải thích."),

    # Batch 12 — ~55:30 to ~60:30 (EN blocks 1248-1330)
    (1248, "Đây là Larry Ellison."),
    (1252, "Larry Ellison có lẽ không đọc sách, có lẽ chưa từng đọc Albert Pike, chưa từng đọc Brzezinski."),
    (1255, "Nhưng ông là một trong những người đàn ông quyền lực nhất ở Mỹ vì ông sáng lập một công ty tên Oracle."),
    (1256, "Oracle."),
    (1262, "Và đây là ông cùng Donald Trump công bố một thứ gọi là Chiến dịch Stargate, họ sẽ xây các trung tâm dữ liệu khắp nước Mỹ để tạo ra nhà nước A I giám sát của họ."),
    (1265, "Larry Ellison là một trong những người quyền lực nhất thế giới, nhưng quá khứ của ông rất rất thú vị."),
    (1267, "Ông sáng lập công ty Oracle, khi đó được gọi là R S I."),
    (1269, "Đây là từ cuốn tiểu sử Larry Ellison có tên The Difference Between God and Larry Ellison."),
    (1272, "Ông nói trong năm năm đầu công ty của ông tệ khủng khiếp."),
    (1275, "Họ là một công ty cơ sở dữ liệu thiết kế để thu thập dữ liệu rồi tổ chức theo cách hữu ích cho doanh nghiệp và chính phủ."),
    (1278, "Nhưng họ tệ đến mức nếu bạn đưa dữ liệu vào máy của họ, họ làm mất hết dữ liệu."),
    (1279, "Họ đơn giản là vô năng."),
    (1281, "Nhưng khách hàng của họ là ai? Là C I A và Hải quân, những bên có ngân sách vô tận."),
    (1284, "Công ty vô năng phá dữ liệu nhưng chính phủ vẫn tiếp tục ủng hộ."),
    (1285, "Alan đọc giúp."),
    (1288, "Điều buồn cười là các khách hàng đầu tiên không thực sự bận tâm chuyện mất tiền hay mất dữ liệu."),
    (1290, "Dù R S I không bao giờ thực sự giao được thứ C I A muốn, cơ quan này không khó chịu."),
    (3444.37, "Kỹ sư Kirk Bradley nhớ một nhân viên C I A nói: chúng tôi mua những thứ này dù biết rõ nó sẽ không hoạt động."),
    (1294, "Chúng tôi đang mua một ý tưởng."),
    (1296, "Băng từ Orate của George cũng không làm hài lòng Hải quân."),
    (1297, "Nhưng không sao."),
    (1299, "Chúng tôi đang mua một chiếc Wright Flyer với kỳ vọng có lẽ vài năm nữa sẽ có một hãng hàng không."),
    (1302, "John Scale của Hải quân nói Hải quân hiểu rằng Oracle có thể đổ vỡ bất cứ lúc nào, nhưng vẫn hứng thú thử cho nó cất cánh."),
    (1304, "Scale nói với một chút mỉa mai, điều này thực sự khó hiểu."),
    (1308, "C I A và Hải quân, lẽ ra bạn thuê một công ty vì công ty đó làm rẻ hơn, nhanh hơn, hiệu quả hơn bạn có thể tự làm, phải không?"),
    (1311, "Nhưng với Oracle, điều xảy ra là nó tốn của họ rất nhiều tiền, họ không nhận được thứ họ muốn."),
    (1314, "Họ phải đổ nguồn lực của mình ra để tạo ra Oracle, họ phải giúp Oracle hình thành."),
    (3502.00, "Vậy Oracle và Larry Ellison đều là sản phẩm tạo ra của C I A và Hải quân."),
    (1316, "Vì sao họ làm vậy?"),
    (1318, "Đó là một câu hỏi rất khó hiểu, tôi không biết câu trả lời."),
    (1320, "Có thể vì Larry Ellison là một anh chàng rất cuốn hút."),
    (1322, "Có thể vì ông có họ hàng làm cho C I A."),
    (1323, "Có thể vì ông gặp may."),
    (1325, "Ai biết, nhưng đây là một sự thật rất khó hiểu về việc các công ty như Oracle khởi đầu."),
    (1327, "Ta cũng sẽ nói về người này, Peter Thiel."),
    (1328, "Peter Thiel có lẽ là một trong những người đàn ông quyền lực nhất ở Mỹ hiện nay."),
    (3537.45, "Tôi nghĩ ông thực sự quyền lực hơn nhiều so với Elon Musk."),

    # Batch 13 — ~60:30 to ~65:30 (EN blocks 1331-1491)
    (1330, "Tại sao?"),
    (1333, "Vì năm 2016, ông đã nhận ra tiềm năng của Donald Trump và ủng hộ chiến dịch của Trump."),
    (1338, "Ông cũng thấy tiềm năng ở JD Vance, ủng hộ sự nghiệp đầu tư mạo hiểm cũng như cuộc đua thượng viện của Vance, rồi đưa Vance lên làm phó tướng cho Donald Trump."),
    (3563.46, "Và khi đọc Peter Thiel, dù là doanh nhân, thực ra ông đọc lên rất giống một Tam Điểm."),
    (1341, "Thật rất kỳ lạ."),
    (1343, "Đây là từ sách Zero to One của ông."),
    (1344, "Ông nói về cách xây dựng một công ty vĩ đại."),
    (3580.46, "Ông bảo bạn thế này, nếu bạn muốn xây một công ty lớn để cạnh tranh với công ty khác, bạn là kẻ ngốc."),
    (1347, "Cạnh tranh là dành cho kẻ thua cuộc."),
    (1348, "Chủ nghĩa tư bản là dành cho kẻ thua cuộc."),
    (1349, "Cái bạn muốn là độc quyền."),
    (1350, "Cái bạn muốn là chủ nghĩa cộng sản."),
    (1351, "Cái bạn muốn là thống trị."),
    (1353, "Và như vậy bạn cần một bí mật để kiếm tiền."),
    (1354, "Alan đọc giúp, đọc chậm thôi."),
    (1356, "Có hai loại bí mật, bí mật của tự nhiên và bí mật về con người."),
    (1358, "Bí mật tự nhiên tồn tại khắp quanh ta."),
    (1360, "Để tìm thấy, ta phải nghiên cứu một số khía cạnh chưa khám phá của thế giới vật chất."),
    (1362, "Bí mật về con người thì khác, có những điều người ta không biết về chính mình."),
    (1363, "Hoặc những điều họ giấu vì không muốn người khác biết."),
    (1367, "Vậy khi nghĩ về loại công ty nên xây, có hai câu hỏi khác biệt: bí mật nào tự nhiên không nói cho bạn, bí mật nào con người không nói cho bạn?"),
    (1369, "Nếu bạn tìm thấy một bí mật, bạn đối diện một lựa chọn."),
    (1373, "Một số là rộng lượng hơn, như những kẻ ngốc trong truyện của Wagner, kẻ điên đủ liều phơi bày trái tim mình ra và bộc lộ cảm xúc cho đám đông bên dưới."),
    (1375, "Loài người đã luôn đóng đinh và thiêu họ."),
    (1378, "Trừ khi bạn có niềm tin hoàn toàn quy ước, hiếm khi nào là ý hay để kể cho mọi người mọi điều bạn biết."),
    (1379, "Vậy bạn kể cho người cần nghe và không hơn."),
    (1382, "Trong thực tế luôn có điểm vàng giữa kể với không ai và kể với mọi người, và đó chính là một công ty."),
    (1383, "Những doanh nhân giỏi nhất biết điều này."),
    (1385, "Mọi doanh nghiệp vĩ đại đều xây quanh một bí mật giấu khỏi bên ngoài."),
    (1387, "Một công ty vĩ đại là một âm mưu thay đổi thế giới."),
    (1388, "Khi bạn chia sẻ bí mật, người nhận trở thành đồng phạm."),
    (1389, "Làm sao bạn xây một công ty vĩ đại?"),
    (1390, "Bạn tạo ra một hội kín."),
    (1392, "Và hội kín là gì? Bạn tiếp cận huyền học."),
    (1396, "Nếu các bạn thực sự muốn kiếm rất nhiều tiền, đừng dành thời gian lập trình hay đi tìm công nghệ tốt nhất."),
    (3700.47, "Đừng làm vậy, đó là phí thời gian."),
    (1397, "Hãy nhìn vào huyền học."),
    (1398, "Hãy giải mã các bí mật của loài người."),
    (1401, "Hãy giải mã bí mật của huyền học và xây công ty quanh ý tưởng đó, rồi bạn sẽ đi đến thống trị."),
    (1405, "Ông cũng nói rất rõ thế này: nếu các bạn muốn khởi nghiệp, hãy lập một tôn giáo trước đã."),
    (1406, "Alan đọc giúp."),
    (1409, "Các startup tốt nhất có thể coi là dạng giáo phái cực đoan hơi nhẹ một chút."),
    (1411, "Khác biệt lớn nhất là giáo phái có xu hướng cuồng tín sai về điều gì đó quan trọng."),
    (1414, "Người trong một startup thành công thì cuồng tín đúng về điều gì đó mà người ngoài đã bỏ lỡ."),
    (1416, "Các bạn sẽ không học được những bí mật đó từ tư vấn viên."),
    (1419, "Và các bạn không cần lo nếu công ty của mình không hợp lý đối với các chuyên gia quy ước."),
    (1420, "Thà bị gọi là giáo phái hay thậm chí mafia."),
    (1422, "Có hợp lý không các bạn?"),
    (1424, "Ông đang nói thẳng giờ đây: hãy mở một tôn giáo hoặc một mafia, không quan trọng."),
    (1427, "Peter Thiel quan trọng vì ông là cố vấn cho hai cá nhân: Mark Zuckerberg và Sam Altman."),
    (1432, "Hãy nhớ từ tuần trước, ta đọc cuốn Empire of AI của Karen Hao, nơi Sam Altman nói rằng những nhà sáng lập thành công nhất không khởi đầu để tạo công ty."),
    (1433, "Họ trong sứ mệnh tạo ra cái gì đó gần với tôn giáo hơn."),
    (1435, "Vậy ông về cơ bản đang dùng lời của thầy mình, Peter Thiel."),
    (1439, "Đây cũng là điều Altman nói: người ta nói về việc cần bao nhiêu năng lượng để huấn luyện một mô hình A I, nhưng cũng tốn nhiều năng lượng để đào tạo một con người."),
    (1442, "Mất khoảng 20 năm đời người và toàn bộ thức ăn bạn ăn trong thời gian đó trước khi bạn trở nên thông minh."),
    (1444, "Những người này thực sự không thấy có khác biệt giữa A I và con người."),
    (1445, "Bạn chỉ là năng lượng để khai thác."),
    (1447, "Bạn chỉ là một thứ năng lượng tôi cần biến thành một khối lập phương để tạo ngôi đền thiêng liêng của lý trí."),
    (1451, "Đây là một người bạn khác của Peter Thiel tên Alexander Karp, hai người cùng sáng lập công ty Palantir."),
    (1452, "Palantir là gì?"),
    (1453, "Palantir là công ty A I giám sát tối thượng."),
    (1454, "Oracle tạo ra cơ sở dữ liệu."),
    (1456, "Của thông tin, mọi thứ về bạn đều nằm trong cơ sở dữ liệu Oracle."),
    (1458, "Palantir thì lấy thông tin này và dự đoán cách bạn sẽ hành xử."),
    (1461, "Và đây là tuyên ngôn Palantir gọi là The Technological Republic."),
    (1463, "Họ không phải Tam Điểm, nhưng cũng có thể coi như là."),
    (1466, "Đây là tuyên ngôn, về cơ bản nói rằng chúng ta cần tạo ra một chế độ kỹ trị, đó là tất cả ý của nó."),
    (1468, "Ta sẽ tạo ra một chế độ kỹ trị, một nhà nước."),
    (1469, "Và đó là điều tốt."),
    (1471, "Và tôi sẽ kết thúc bằng điều này."),
    (1474, "Peter Thiel mấy năm qua đã diễn thuyết khắp thế giới về kẻ chống Chúa."),
    (1475, "Kẻ chống Chúa là gì?"),
    (1479, "Kẻ chống Chúa lên nắm quyền bằng cách lợi dụng nỗi sợ công nghệ và dụ ta vào sự thuần phục với khẩu hiệu hòa bình và an toàn."),
    (1481, "Kẻ chống Chúa là bất kỳ ai và mọi người chống lại nhà nước A I giám sát dân."),
    (1483, "Có thể bạn nghĩ, khoan, chẳng phải hợp lý hơn khi tin rằng nhà nước A I chính là kẻ chống Chúa?"),
    (1485, "Không, Peter Thiel đang nói ngược lại các bạn ạ."),
    (1487, "Nếu bạn chống lại nhà nước, bạn là kẻ chống Chúa."),
    (1488, "Kẻ chống Chúa là cái ác."),
    (1489, "Vì vậy ta phải tiêu diệt những người đó."),
    (1490, "Ai ngăn ta xây nhà nước A I đều là cái ác thuần túy."),
    (1492, "Và một khi bạn hiểu điều này, ta sẽ đạt được đế chế thiêng liêng của lý trí."),

    # Batch 14 — ~65:30 to end (EN blocks 1493-1542)
    (1493, "Có câu hỏi nào không các bạn?"),
    (1496, "Vậy ta có thể hiểu Hội Tam Điểm, đế chế của lý trí, như một dạng tẩy não không?"),
    (1497, "Được."),
    (1502, "Hội Tam Điểm là một nhóm người thực hành những điều nhất định, và ở trung tâm là tầm nhìn mạt thế học cố đạt được sự kết thúc của thế giới."),
    (1505, "Đó là một chính phủ một thế giới đặt tại Jerusalem."),
    (1508, "Nơi mọi người tuân lệnh chính phủ này, và nếu bạn tuân lệnh thì thế giới sẽ hoàn hảo."),
    (1509, "Đúng vậy."),
    (1511, "Vậy làm sao khiến người ta tuân lệnh? A I, phải không?"),
    (1513, "Bạn không muốn tập thể dục, không muốn học hành."),
    (1515, "Bạn không muốn đi làm và đóng thuế."),
    (1516, "Vậy ta hãy có một A I trong đầu bạn, một chuyến đi xe đạp trong đầu bạn nhắc rằng không, Vincent, bạn nên đóng thuế."),
    (1518, "Không, Vincent, bạn không nên lái xe trong lúc say."),
    (1519, "Đó là ý tưởng."),
    (1521, "Nó nói về thuật giả kim, sự hoàn thiện con người."),
    (1522, "Cố biến bạn thành một con robot ngoan ngoãn có thể lập trình được."),
    (1523, "Vô lý đúng không?"),
    (1526, "Nhưng nó là điều tốt vì một khi làm vậy, sẽ có hòa bình, sẽ có hạnh phúc."),
    (1527, "Sẽ có an toàn, đó là điều tốt."),
    (1530, "Vâng, nhưng nếu đó là điều tốt thì tính chủ thể của con người còn có ý nghĩa gì khi A I kiểm soát hoàn toàn bạn?"),
    (1532, "Tính chủ thể của con người là xấu vì nó dẫn đến tội lỗi."),
    (1533, "Nó dẫn đến sai lầm, dẫn đến hỗn loạn."),
    (1534, "Bạn hiểu chứ?"),
    (1535, "Nếu tất cả ta đều nghĩ giống nhau, thế giới mới hoàn hảo."),
    (1537, "Bây giờ ta đạt được tình huynh đệ chung của loài người, ta đạt được Chúa nếu mọi người nghĩ giống nhau."),
    (1538, "Và đó là điều A I có thể làm cho ta."),
    (1539, "Còn câu hỏi nào nữa không?"),
    (1540, "Ổn rồi, Putin sẽ đến Bắc Kinh tối nay."),
    (1542, "Vậy thứ Năm này ta sẽ bàn về Putin nhé."),
]

en_blocks = parse_en(EN)
en_by_idx = {b[0]: b for b in en_blocks}

# Validate translations
max_idx = max(b[0] for b in en_blocks)
print(f"EN max idx: {max_idx}")
print(f"Translations count: {len(TRANSLATIONS)}")

# Build VN
# Each entry's "marker" can be:
#   int  → last EN block idx (use that block's end time)
#   float → literal end time in seconds (used when splitting a block across multiple VN sentences)
output = []
prev_end_sec = en_by_idx[1][3]  # start of EN block 1
prev_end_idx = 0
errors = []
for i, (marker, vn_text) in enumerate(TRANSLATIONS, start=1):
    if isinstance(marker, float):
        end_sec = marker
        start_sec = prev_end_sec
        if end_sec <= start_sec:
            errors.append(f"Block {i}: float end {end_sec:.3f} <= prev {prev_end_sec:.3f}")
            continue
        start_ts = sec_to_ts(start_sec)
        end_ts = sec_to_ts(end_sec)
        output.append(f"{i}\n{start_ts} --> {end_ts}\n{vn_text}\n")
        prev_end_sec = end_sec
        # Don't change prev_end_idx — next int marker will keep aligned
    else:
        last_idx = marker
        first_idx = prev_end_idx + 1
        if last_idx < first_idx:
            errors.append(f"Block {i}: last_idx {last_idx} < first_idx {first_idx}")
            continue
        if last_idx not in en_by_idx:
            errors.append(f"Block {i}: last_idx {last_idx} not found")
            continue
        # Start: previous end (carry over from float if used), or EN block first_idx start
        if abs(prev_end_sec - en_by_idx[first_idx][3]) < 0.5 or prev_end_sec < en_by_idx[first_idx][3]:
            start_sec = en_by_idx[first_idx][3]
        else:
            start_sec = prev_end_sec  # we're mid-block from a float split
        end_sec = en_by_idx[last_idx][4]
        start_ts = sec_to_ts(start_sec)
        end_ts = sec_to_ts(end_sec)
        output.append(f"{i}\n{start_ts} --> {end_ts}\n{vn_text}\n")
        prev_end_sec = end_sec
        prev_end_idx = last_idx

if errors:
    print("ERRORS:")
    for e in errors[:20]:
        print(" ", e)

print(f"Wrote {len(output)} VN blocks. Last EN idx covered: {prev_end_idx}/{max_idx}")

with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(output))
print(f"OUT: {OUT}")
